# Site settings
title: CardVerse by Jatan Pandya
tag_text: CardVerse
description: 'A machine that authenticates, grades, and sorts Magic: The Gathering Card.'
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
